In [13]:
!pip install transformers

In [14]:
from transformers import pipeline

In [15]:
summarizer = pipeline("summarization")

In [16]:
ARTICLE = """Berkshire is the largest owner of American-based property, plant, and equipment with fixed assets of $154 billion, followed by AT&T, at $127 billion. That Berkshire fact alone means it is an asset-heavy company that invests a lot of capital, not necessarily generating the best-earning results or even a good investment.

As most business college students learn in school, good returns can come from companies with minimal assets in high-margin businesses that have expanding topline growth. Simply being asset-heavy is not a reflection of a beauty contest."""

In [17]:
summarizer(ARTICLE, max_length=300, min_length=10, do_sample=False)

Your max_length is set to 300, but you input_length is only 117. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)


[{'summary_text': ' Berkshire is the largest owner of American-based property, plant, and equipment with fixed assets of $154 billion, followed by AT&T, at $127 billion . That Berkshire fact alone means it is an asset-heavy company that invests a lot of capital .'}]

Berkshire is the largest owner of American-based property, plant, and equipment with fixed assets of $154 billion, followed by AT&T, at $127 billion . That Berkshire fact alone means it is an asset-heavy company that invests a lot of capital

In [18]:
print(len(ARTICLE))
print(len("Berkshire is the largest owner of American-based property, plant, and equipment with fixed assets of  154 billion, followed by AT&T, at 127 billion . That Berkshire fact alone means it is an asset-heavy company that invests a lot of capital"))

557
240


2분의 1로 문장이 줄어들었다! 

---
do_sample을 True로 해보자


In [19]:
summarizer(ARTICLE, max_length=100, min_length=10, do_sample=True)

[{'summary_text': ' Berkshire is the largest owner of American-based property, plant, and equipment with fixed assets of $154 billion . AT&T is the second-largest U.S. company, followed by Berkshire at $127 billion . Good returns can come from companies with minimal assets in high-margin businesses that have expanding topline growth . Simply being asset-heavy is not a reflection of a beauty contest .'}]

Berkshire is the largest owner of American-based property, plant, and equipment with fixed assets of $154 billion . AT&T, at $127 billion, is the second-largest U.S.-based company, followed by Berkshire . Good returns can come from companies with minimal assets in high-margin businesses that have expanding topline growth 

Berkshire는 고정 자산 1,540 억 달러를 보유한 미국 기반 부동산, 플랜트 및 장비의 최대 소유주입니다. AT & T (1,270 억)는 미국에서 두 번째로 큰 회사이며 Berkshire 뒤를 이었습니다. 외형 성장이 확대되고있는 고수익 사업에서 최소한의 자산을 가진 회사에서 좋은 수익을 얻을 수 있습니다.

성능이 굉장히 괜찮다! 

---



In [20]:
from transformers import pipeline

def summarize (Artcles):
  return summarizer(Artcles, max_length=300, min_length=10, do_sample=False)

In [21]:
summarize(ARTICLE)

Your max_length is set to 300, but you input_length is only 117. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)


[{'summary_text': ' Berkshire is the largest owner of American-based property, plant, and equipment with fixed assets of $154 billion, followed by AT&T, at $127 billion . That Berkshire fact alone means it is an asset-heavy company that invests a lot of capital .'}]

2021년 버크셔 헤서웨이의 주주서한을 불러오자 

In [22]:
from google.colab import drive
drive.mount('/gdrive', force_remount=True)

Mounted at /gdrive


In [23]:
import numpy as np
import pandas as pd

df = pd.read_excel('/gdrive/MyDrive/birk2021.xlsx')
df.head(30)

id                                           document
0    1  Berkshire earned $42.5 billion in 2020 accordi...
1    2  Operating earnings are what count most, even d...
2    3  The two GAAP components pertaining to capital ...
3    4  As I’ve emphasized many times, Charlie and I v...
4    5  What’s out of sight, however, should not be ou...
5    6  Of course, some of our investees will disappoi...
6    7  The final component in our GAAP figure – that ...
7    8  No one misled me in any way – I was simply too...
8    9  I believe I was right in concluding that PCC w...
9   10  Two Strings to Our Bow Berkshire is often labe...
10  11  Over time, conglomerates have generally limite...
11  12  Beyond that, as conglomerateurs dipped into th...
12  13  Often, the tools for fostering the overvaluati...
13  14  Investing illusions can continue for a surpris...
14  15  Eventually, of course, the party ends, and man...
15  16  Charlie and I want our conglomerate to own all...
16  17  For those reasons, our conglomerate will remai...
17  18  If that strategy requires little or no effort ...
18  19  On page A-1 we list Berkshire’s subsidiaries, ...
19  20  Most of Berkshire’s value, however, resides in...
20  21  The largest in value is our property/casualty ...
21  22  Overall, the insurance fleet operates with far...
22  23  And bonds are not the place to be these days. ...
23  24  Some insurers, as well as other bond investors...
24  25  Berkshire now enjoys $138 billion of insurance...
25  26  I have repetitiously – some might say endlessl...
26  27  Our second and third most valuable assets – it...
27  28  I’ll have more to say about BNSF and BHE later...
28  29  Last year we demonstrated our enthusiasm for B...
29  30  Following criteria Charlie and I have long rec...

2021 주주서한을 라이브러리를 활용해 요약해준다

In [24]:
df = df['document'].apply(summarize)
df

Your max_length is set to 300, but you input_length is only 123. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 300, but you input_length is only 104. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 300, but you input_length is only 81. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 300, but you input_length is only 126. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 300, but you input_length is only 120. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 300, but you input_length is only 100. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 300, but you input_length is only 58. You might con

0      [{'summary_text': ' Berkshire earned $42.5 bil...
1      [{'summary_text': ' Operating earnings are wha...
2      [{'summary_text': ' The two GAAP components pe...
3      [{'summary_text': ' Charlie and Charlie view B...
4      [{'summary_text': ' Unrecorded retained earnin...
                             ...                        
110    [{'summary_text': ' See’s peanut brittle and f...
111    [{'summary_text': ' This year, on May 1st, we ...
112    [{'summary_text': ' Our formal meeting will co...
113    [{'summary_text': ' This year our meeting will...
114    [{'summary_text': ' Berkshire can't wait to ge...
Name: document, Length: 115, dtype: object

데이터프레임으로 만들어주기


In [ ]:
df = df.reset_index(drop=True).to_frame('document')

In [34]:
df

document
0    [{'summary_text': ' Berkshire earned $42.5 bil...
1    [{'summary_text': ' Operating earnings are wha...
2    [{'summary_text': ' The two GAAP components pe...
3    [{'summary_text': ' Charlie and Charlie view B...
4    [{'summary_text': ' Unrecorded retained earnin...
..                                                 ...
110  [{'summary_text': ' See’s peanut brittle and f...
111  [{'summary_text': ' This year, on May 1st, we ...
112  [{'summary_text': ' Our formal meeting will co...
113  [{'summary_text': ' This year our meeting will...
114  [{'summary_text': ' Berkshire can't wait to ge...

[115 rows x 1 columns]

위 excel파일을 저장해주고

In [35]:
df.to_excel('/gdrive/MyDrive/Colab Notebooks/2021letterforstockon.xlsx', index=False) 

요약이 잘 되었는지 지표를 잘 모르겠음 합쳐서 비교해보아야함

In [40]:
df_origin = pd.read_excel('/gdrive/MyDrive/birk2021.xlsx')
df_origin.head(), df_origin.shape

(   id                                           document
 0   1  Berkshire earned $42.5 billion in 2020 accordi...
 1   2  Operating earnings are what count most, even d...
 2   3  The two GAAP components pertaining to capital ...
 3   4  As I’ve emphasized many times, Charlie and I v...
 4   5  What’s out of sight, however, should not be ou..., (115, 2))

형태가 같은건 사실 확인 안해봐도 아니까 합쳐주자! 

In [47]:
result = pd.concat([df, df_origin], axis = 1)
result

document  ...                                           document
0    [{'summary_text': ' Berkshire earned $42.5 bil...  ...  Berkshire earned $42.5 billion in 2020 accordi...
1    [{'summary_text': ' Operating earnings are wha...  ...  Operating earnings are what count most, even d...
2    [{'summary_text': ' The two GAAP components pe...  ...  The two GAAP components pertaining to capital ...
3    [{'summary_text': ' Charlie and Charlie view B...  ...  As I’ve emphasized many times, Charlie and I v...
4    [{'summary_text': ' Unrecorded retained earnin...  ...  What’s out of sight, however, should not be ou...
..                                                 ...  ...                                                ...
110  [{'summary_text': ' See’s peanut brittle and f...  ...  Yahoo streamed the proceedings to a record-siz...
111  [{'summary_text': ' This year, on May 1st, we ...  ...  This year, on May 1st, we are planning to go o...
112  [{'summary_text': ' Our formal meeting will co...  ...  Our formal meeting will commence at 5:00 p.m. ...
113  [{'summary_text': ' This year our meeting will...  ...  And now – drum roll, please – a surprise. This...
114  [{'summary_text': ' Berkshire can't wait to ge...  ...  Join us via Yahoo. Direct your really tough qu...

[115 rows x 3 columns]

대충 비슷한거 같으니 이제 긍정인지 부정인지 확인하러 가자! 